name: Infra podfy user application

env:
  product_name: podfy-user-worker
  service_name: services-infra

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    env:
       working-directory: ./pipeline   
    runs-on: ubuntu-latest
    steps:  
     - uses: actions/checkout@master
     - name: root directory
       run: ls -R
       working-directory: ${{env.worker-directory}}          
     - name: Configure AWS credentials
       id: credentialsaws
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
     - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions       
       run: |
           parameters=($(jq -r '.Parameters[] | [.ParameterKey, .ParameterValue] | "\(.[0])=\(.[1])"' ./pipeline/parameters.json))
           echo ${parameters[@]}
           aws cloudformation deploy \
           --template-file ./pipeline/template.yaml \
           --parameter-overrides  ${parameters[@]} \
           --stack-name ${{env.service_name}}-${{env.product_name}}
